language: c
os:
  - linux
  - osx
env:
  - PATH=./racket/bin:$PATH
  - PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-places"
  - PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-futures"
  - PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-extflonum"
  - PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit"
  - PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit --disable-places"
  - PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit --disable-extflonum"
compiler:
  - gcc
  - clang
# Just run tests for the core
script:
  - make CPUS="2" PKGS="racket-test db-test unstable-flonum-lib net-test" CONFIGURE_ARGS_qq="$RACKET_CONFIGURE_ARGS"
  - raco test -l tests/racket/test
  - racket -l tests/racket/contract/all
  - raco test -l tests/json/json
  - raco test -l tests/file/main
  - raco test -l tests/net/head
  - raco test -l tests/net/uri-codec
  - raco test -l tests/net/url
  - raco test -l tests/net/url-port
  - raco test -l tests/net/encoders
  - raco test -l tests/openssl/basic
  - raco test -l tests/openssl/https
  - raco test -l tests/match/plt-match-tests
  - raco test -l tests/zo-path
  - raco test -l tests/xml/test
  - raco test -l tests/db/all-tests
notifications:
  irc: "chat.freenode.net#racket-dev"
  email: 
    recipients: 
      - samth@racket-lang.org
      - robby@racket-lang.org
    on_success: change

